### ISSUE TITLE
lancement connecthys KO

### ISSUE THREAD

**Issue by cyrillebonnaud** [Noethys/Connecthys#11]
Installer python et pycrypto.
Copier le répertoire connecthys à la racine du serveur.
Exécuter python run.py

Obtenu :
```
Traceback (most recent call last):
File "run.py", line 92, in <module>
from application import app
File "/apps/connecthys/application/__init__.py", line 30, in <module>
from data.config import Config_application
ImportError: No module named config
```

**Comment by cyrillebonnaud** [comment]
C'est peut-être lié à ce commit ?

https://github.com/Noethys/Connecthys/commit/cf5b3b7b56db75c3fb6d65f512a39391914607a3
