### ISSUE TITLE
Erreur lors du lancement de Connecthys

### ISSUE THREAD

**Issue by neoclust** [Noethys/Connecthys#23]
Lancement de Connecthys...
serveur=None host=0.0.0.0 port=5000
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/connecthys/run.py", line 92, in <module>
    from application import app
  File "/usr/lib/python3.8/site-packages/connecthys/application/__init__.py", line 23, in <module>
    import updater
ModuleNotFoundError: No module named 'updater

**Comment by neoclust** [comment]
en changeant l'import en 

from . import updater 

permet de passer plus loin que cette étape.
