### ISSUE TITLE
Le serveur ne se lance pas

### ISSUE THREAD

**Issue by tomgraal** [Noethys/Connecthys#26]
Bonjour,
j'ai bien suivi la procédure pour installer connecthys via noethys sur windows10, cependant et ce malgré de nombreuses tentatives un message d'erreur disant que le serveur ne se lance pas apparait à chaque fois. Le téléchargement du log est impossible et donc aucune explication est donné pour corriger le problème. J'invite le développeur de l'application de tester la procédure indiquer sur le readme.md sur une machine w10 vierge et constater le problème par eux-même.
J'ai également tenter l'expérience sur ubuntu sans succès.
Cordialement.

**Comment by Noethys** [comment]
Bonjour,
Il y avait en effet des dépendances obsolètes. J'ai fait quelques corrections qui semblent désormais faciliter de nouveau l'installation (Testé sur Windows 11).
Bonne journée.

**Comment by juluanb** [comment]
Bonjour,
J'ai effectué des tests sur la dernière version disponible sur le dépôt et j'ai également une erreur au démarrage du serveur, qui semble aussi lié à un problème de dépendance (n'étant pas expert Python, je laisse à d'autre le soin d'interpréter :)):
```
Traceback (most recent call last):
  File "/noethys/Connecthys/connecthys/run.py", line 92, in <module>
    from application import app
  File "/noethys/Connecthys/connecthys/application/__init__.py", line 24, in <module>
    import updater
ModuleNotFoundError: No module named 'updater'
Lancement de Connecthys...
serveur=None host=0.0.0.0 port=5000
```

J'ai construit une image Docker pour faire ce test. Voici le Dockerfile:
```
FROM python:3.11.2

RUN useradd -d /noethys noethys
RUN apt-get update && apt-get install -y git
RUN mkdir -p /noethys
RUN chown -R noethys:noethys /noethys
USER noethys
RUN cd /noethys \
        && git clone https://github.com/Noethys/Connecthys.git \
        && cd Connecthys \
        && pip3 install -r requirements.txt

VOLUME /noethys/Connecthys
WORKDIR /noethys/Connecthys

CMD ["python3","connecthys/run.py"]
```

Pour reproduire l'erreur:
```bash
docker build -t connecthys:latest .
docker run -p 5000:5000 connecthys:latest
```

**Comment by Noethys** [comment]
Bonjour,

Je ne vois pas trop d'où cela peut venir. Avez-vous essayer de faire : 
cd /noethys/Connecthys/connecthys/
depuis : run.py

**Comment by yledoare** [comment]
Bonjour,

il faut effectivement écrire  

```
WORKDIR /noethys/Connecthys/connecthys
CMD ["python3","run.py"]

```
https://github.com/yledoare/docker-images/blob/master/noethys/Dockerfile
